apiVersion: v1
kind: ConfigMap
metadata:
  name: securedns-conf
  namespace: default
data:
  01-pihole.conf: |
    addn-hosts=/etc/pihole/gravity.list
    addn-hosts=/etc/pihole/black.list
    addn-hosts=/etc/pihole/local.list

    localise-queries

    no-resolv

    cache-size=10000

    log-queries=extra
    log-facility=/var/log/pihole.log

    local-ttl=2

    log-async
    server=127.0.0.1#54
    interface=eth0
  external.conf: |
    $HTTP["host"] == "securedns.pepperprovesapoint.com" {
    # Ensure the Pi-hole Block Page knows that this is not a blocked domain
    setenv.add-environment = ("fqdn" => "true")
    }
